---
title: "finalized-paper"
format: html
editor: visual
---

## Report

Introduction:

_Sarracenia_ are carnivorous pitcher plants that use their pitcher-shaped leaves to catch arthropod prey for nutrition (Milne and Waller 1). Oftentimes, the majority of their diet is made up of spiders, however _Sarracenia_ also feed on insects, mites, mollucks, and occcasionally, even small verterbrates (Milne 1). This carnivorous pitcher plant has many uses for humans including treatments for type 2 diabetes and tuberculosis-like symptoms (Huang et al. 1). Therefore, understanding what morphological, physiological, or taxonomic characteristics predict biomass may be useful if these pitcher plants began to be used for medical purposes. Moreover, understanding what factors predict pitcher plant biomass can also be helpful to understand how climate change may affect these plants if certain pitcher plant growth biomass factors are depleted. As a result, this statistical analysis revolves around the question of how _Sarracenia_ characteristics predict biomass. We are testing the null hypothesis that _Sarracenia_ characteristics do not predict biomass against the alternative hypothesis that _Sarracenia_ characteristics do predict biomass. 


Methods:

The data from the dataset was compiled by conducting an experiment in which two plants of each Sarracenia species (10 Sarracenia species in total) were assigned to one of six feeding levels ranging from 0 - 0.25g of finely ground wasps per feeding (for small species), 0 - 0.5g for intermediate sized species, and 0 - 1.0g for large species (Ellison and Farnsworth). The plants were fed once a week for a total of 7 weeks. In addition, aboveground size and photosynthetic rate were measured before treatments started (metadata). To organize these data, the column names were made cleaner using the clean() function and only certain columns were selected (totmass, species, feedlevel, sla, chlorophyll, amass, num_lvs, num_phyll). 

Next, a visualization of the missing data were created, which showed there were missing data in the sla, chlorophyll, amass, num_lvs, and num_phylls column. Therefore, the missing data were dropped from the dataset and a new subset of data was created without the missing data. 

To determine the Pearson's correlation between variables, we calculated Pearson's r and visually represented correlation using a correlation plot. Pearson's r was calculated by computing the covariances, or correlations, between two variables (such as species versus biomass or chlorophyll versus number of pitcher plants) which was done by taking the covariance of the two variables and dividing them by the product of their standard deviations. This was done for every pair of variables, so that each variable was compared to itself as well as each variable measured.  

To determine the relationships between variables, a pairs plot was created, comparing each variable to itself and every variable measured. The results were formatted into several visualizations that showed the relationships between them. 

In addition, to determine how species and physiological characteristics predict biomass, we fit multiple linear models. The null model did not include any predictors in the model, while the full model included all predictors in the model. We visually assessed the normality and homoskedasticity of residuals using diagnostic plots for the full model. We also tested for normality using the Shapiro-Wilk test and tested for for homoskedasticity using the Breusch-Pagan test. For the original data, this resulted in non-normality and heteroscedasticity in the residuals, therefore, the data was transformed into its natural log form to create normality and homoscedasticity in the residuals (only the response variable was transformed, not the predictors). The same tests were run for normality and homoscedasticity using the transformed data and the assumptions for the full model were met. 

Works Cited:

https://bioone.org/journals/southeastern-naturalist/volume-11/issue-4/058.011.0402/The-Purple-Pitcher-Plant-as-a-Spider-Oviposition-Site/10.1656/058.011.0402.full 

https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.2504

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9269354/#:~:text=The%20carnivorous%20pitcher%20plant%20Sarracenia%20purpurea%20exhibits%20many%20ethnobotanical%20uses,diabetes%20and%20tuberculosis%2Dlike%20symptoms.

Ellison, A. and E. Farnsworth. 2021. Effects of Prey Availability on Sarracenia Physiology at Harvard Forest 2005 ver 18. Environmental Data Initiative. https://doi.org/10.6073/pasta/26b22d09279e62fd729ffc35f9ef0174 (Accessed 2023-06-01).
